language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/meetings
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "meetings";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./meetings/manage.py test meetings
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: meetings-dev
    qa: meetings-qa
    prod: meetings-prod
  on:
    repo: sychsergiy/ PrettyMeetings
  run:
    - "./meetings/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true

cache: pip
