# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period', models.CharField(choices=[('day', 'Every day'), ('week', 'Every week'), ('month', 'Every month'), ('year', 'Every year')], max_length=120)),
                ('category', models.CharField(choices=[('CAN', 'Can'), ('BETTER_ANOTHER_TIME', 'Better another time'), ('MAYBE', 'Maybe'), ('CANNOT', 'Can not')], max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
